name: CSS linter
run-name: ${{ github.actor }} lintering css code🚀
on: [ push ]
jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: node -v
      - run: sudo apt install npm
      - run: npm -v
      - run: npm install -g csslint
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -la ${{ github.workspace }}
      - run: csslint ./**/*.css