name: HTML linter
run-name: ${{ github.actor }} lintering html code🚀
on: [push]
jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: node -v
      - run: sudo apt install npm
      - run: npm -v
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -la ${{ github.workspace }}
      - run: htmlhint ./**/*.html