name: Linter
run-name: ${{ github.actor }} lintering code🚀
on: [ push ]
jobs:
  css:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: sudo apt install npm
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install stylelint-config-standard --save-dev
      - run: npm init stylelint -y
      - run: npx stylelint "**/*.css"

  html:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: sudo apt install npm
      - run: npm install htmlhint -g
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: htmlhint ./**/*.html